dc_config_folder: /etc/docker
dc_volumes_folder: /opt/docker
docker_subnet: 172.19.0.0/24
docker_gateway: 172.19.0.0/24
docker_containers:
  - { 'name': 'openldap', 'image': 'openldap', 'image_version': '2.4.0', 'env_file':'.env_openldap', 'volumes':['{{dc_volumes_folder}}/openldap/var:/var/lib/ldap'], 'ports':['389:389'], 'links':[''], 'entrypoints':[''], 'user': '', 'network_mode':'bridge', 'ip_address': '172.19.0.2' }

docker_config_files:
    - {'source_file': 'files/dhcp/dhcpd.conf', 'dest_path': '{{dc_volumes_folder}}/dhcp/etc','dest_file':'dhcpd.conf'}

docker_templates_folder: templates


    
